files:
  - {
      path: $(find-pkg-share autoware_launch)/config/system/system_diagnostic_monitor/autoware-main.yaml,
    }

edits:
  - { type: remove, path: /autoware/system/duplicated_node_checker }
